# Generated by Django 3.1.3 on 2021-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210120_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isfavorite',
            field=models.BooleanField(default=False),
        ),
    ]
